# Dataset Preparation & Initial EDA

Project: EcoPackAI  
Notebook: dataset_prep.ipynb  

This notebook covers:
- Dataset loading
- Initial exploratory analysis
- Data cleaning & preprocessing
- Dataset readiness for feature engineering

In [52]:
# cell 1 Environment setup
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [53]:
# cell 2 load dataset

material = pd.read_csv(r'C:\Users\Ranjit\OneDrive\Desktop\AI-Powered-Sustainable-Packaging-Recommendation-System\data\raw\material_dataset.csv')
print(" material dataset \n")
material.head()

 material dataset

,Material ID,Packaging Type,Material Type,indusrty use case,Recommended Packaging Use Cases,Supplier Region,Recyclability (%),Recyclability Category,Recycled Content (%),Reusability (%),...,CO2 Emission per kg (estimated),Waste Reduction Impact (%),Sustainability Target Progress (%),Strength mpa,Moisture Resistance Score,Thermal Resistance Score,Cost per Unit (USD),Annual Usage (units),Total Material Weight (tons),Supplier Sustainability Compliance (%)
0,MAT_0001,Cardboard Boxes,Cardboard,"E-commerce, Food & Beverage, Consumer Goods, A...",Last-mile delivery and primary e-commerce pack...,EMEA,98,High,79.0,49.0,...,0.54,61.0,88.0,6.0,5.0,4.0,2.24,101260.0,790.0,85.0
1,MAT_0002,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,APAC,100,High,93.0,31.0,...,0.32,68.0,98.0,3.0,3.0,3.0,1.82,73961.0,545.0,88.0
2,MAT_0003,Steel Racks & Containers,Steel,"Heavy Industrial Components, High-Security Goods","Secure, high-load international shipping and l...",AMERICAS,87,High,78.0,100.0,...,3.25,85.0,79.0,8.0,9.0,9.0,25.00,14649.0,4979.0,88.0
3,MAT_0004,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,ROW,100,High,89.0,31.0,...,0.31,69.0,87.0,1.0,1.0,4.0,2.43,75036.0,656.0,81.0
4,MAT_0005,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,LATAM,100,High,92.0,28.0,...,0.31,61.0,89.0,3.0,2.0,3.0,1.69,69209.0,549.0,81.0

In [54]:
print(" \n product dataset \n")
product = pd.read_csv(r'C:\Users\Ranjit\OneDrive\Desktop\AI-Powered-Sustainable-Packaging-Recommendation-System\data\raw\product_dataset.csv')
product.head()

 product dataset

,product_id,product_name,category,product_weight_kg,fragility_index,shipping_type
0,1,Chocolate Box,Food,0.5,2,Air
1,2,Smartphone,Electronics,0.3,5,Air
2,3,Perfume Bottle,Cosmetics,0.2,4,Road
3,4,Medicine Pack,Pharmacy,0.1,3,Air
4,5,Snack Pack,Food,0.7,2,Road

In [55]:
# cell 3 dataset info
print("\n Material Dataset Info \n")
material.info()

 Material Dataset Info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404 entries, 0 to 403
Data columns (total 23 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Material ID                             404 non-null    object
 1   Packaging Type                          404 non-null    object
 2   Material Type                           404 non-null    object
 3   indusrty use case                       404 non-null    object
 4   Recommended Packaging Use Cases         404 non-null    object
 5   Supplier Region                         404 non-null    object
 6   Recyclability (%)                       404 non-null    int64
 7   Recyclability Category                  404 non-null    object
 8   Recycled Content (%)                    403 non-null    float64
 9   Reusability (%)                         403 non-null    float64
 10  Biodegradation Time (days)              403 non-null    float64
 11  End-of-Life Disposal (%)                403 non-null    float64
 12  Carbon Footprint (kg CO2/unit)          403 non-null    float64
 13  CO2 Emission per kg (estimated)         403 non-null    float64
 14  Waste Reduction Impact (%)              403 non-null    float64
 15  Sustainability Target Progress (%)      403 non-null    float64
 16  Strength mpa                            403 non-null    float64
 17  Moisture Resistance Score               403 non-null    float64
 18  Thermal Resistance Score                403 non-null    float64
 19  Cost per Unit (USD)                     403 non-null    float64
 20  Annual Usage (units)                    403 non-null    float64
 21  Total Material Weight (tons)            403 non-null    float64
 22  Supplier Sustainability Compliance (%)  403 non-null    float64
dtypes: float64(15), int64(1), object(7)
memory usage: 72.7+ KB

In [56]:
print("\n Product Dataset Info \n")
product.info()

 Product Dataset Info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         1500 non-null   int64
 1   product_name       1500 non-null   object
 2   category           1500 non-null   object
 3   product_weight_kg  1500 non-null   float64
 4   fragility_index    1500 non-null   int64
 5   shipping_type      1500 non-null   object
dtypes: float64(1), int64(2), object(3)
memory usage: 70.4+ KB

In [57]:
# cell 4 Data Cleaning & Preprocessing

# 1. Check missing values (documentation purpose)
material.isnull().sum()
material.dropna(inplace=True)

# 2. Standardize column names (snake_case)
material.columns = material.columns.str.lower()

# 3. Ensure no duplicates after drop
material = material.drop_duplicates()

# print("\nAfter cleaning:")
material.shape

(403, 23)

In [58]:
product.isnull().sum()
product.columns = product.columns.str.lower()
product = product.drop_duplicates()
product.shape

(1500, 6)

In [59]:
material.columns = (
    material.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[^\w]+", "_",regex=True)
)
product.columns = (
    product.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[^\w]+", "_",regex=True)
)

In [60]:
material['cost_per_kg'] = material['cost_per_unit_usd_']/((material['total_material_weight_tons_']*1000)/material['annual_usage_units_'])

In [61]:
material['biodegradation_percent'] = (365/material['biodegradation_time_days_'])

In [62]:
material['weight_capacity'] = (material['strength_mpa'] * 0.5 + material['moisture_resistance_score'] * 0.25 + material['thermal_resistance_score'] * 0.25)

In [63]:
material.columns

Index(['material_id', 'packaging_type', 'material_type', 'indusrty_use_case',
       'recommended_packaging_use_cases', 'supplier_region', 'recyclability_',
       'recyclability_category', 'recycled_content_', 'reusability_',
       'biodegradation_time_days_', 'end_of_life_disposal_',
       'carbon_footprint_kg_co2_unit_', 'co2_emission_per_kg_estimated_',
       'waste_reduction_impact_', 'sustainability_target_progress_',
       'strength_mpa', 'moisture_resistance_score', 'thermal_resistance_score',
       'cost_per_unit_usd_', 'annual_usage_units_',
       'total_material_weight_tons_', 'supplier_sustainability_compliance_',
       'cost_per_kg', 'biodegradation_percent', 'weight_capacity'],
      dtype='object')

In [64]:
material.drop(columns=['packaging_type',
       'recommended_packaging_use_cases', 'supplier_region',
       'recyclability_category', 'recycled_content_', 'reusability_',
       'biodegradation_time_days_', 'end_of_life_disposal_',
       'carbon_footprint_kg_co2_unit_',
       'waste_reduction_impact_', 'sustainability_target_progress_',
        'moisture_resistance_score', 'thermal_resistance_score',
       'cost_per_unit_usd_', 'annual_usage_units_',
       'total_material_weight_tons_', 'supplier_sustainability_compliance_'],
       inplace=True)

In [65]:
material.head()

,material_id,material_type,indusrty_use_case,recyclability_,co2_emission_per_kg_estimated_,strength_mpa,cost_per_kg,biodegradation_percent,weight_capacity
0,MAT_0001,Cardboard,"E-commerce, Food & Beverage, Consumer Goods, A...",98,0.54,6.0,0.287117,1.941489,5.25
1,MAT_0002,Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",100,0.32,3.0,0.246989,5.615385,3.00
2,MAT_0003,Steel,"Heavy Industrial Components, High-Security Goods",87,3.25,8.0,0.073554,0.002025,8.50
3,MAT_0004,Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",100,0.31,1.0,0.277953,5.615385,1.75
4,MAT_0005,Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",100,0.31,3.0,0.213048,2.991803,2.75

In [68]:
material.rename(columns={'biodegradation_percent':'biodegradability_percent'},inplace=True)
material.rename(columns={'co2_emission_per_kg_estimated_':'co2_emission_score'},inplace=True)
material.rename(columns={'recyclability_':'recyclability_percent'},inplace=True)

In [69]:
material.columns

Index(['material_id', 'material_type', 'indusrty_use_case',
       'recyclability_percent', 'co2_emission_score', 'strength_mpa',
       'cost_per_kg', 'biodegradability_percent', 'weight_capacity'],
      dtype='object')

In [70]:
# cell 5 Save cleaned datasets
material.to_csv("material_cleaned.csv", index=False)
product.to_csv("product_cleaned.csv", index=False)