In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
import joblib
import os

In [2]:
df = pd.read_csv("data/processed/cleaned_EcoPackAi_dataset.csv")
df.head()

,Material ID,Packaging Type,Material Type,Suitable Product Categories,Recommended Packaging Use Cases,Supplier Region,Recyclability (%),Recyclability Category,Recycled Content (%),Reusability (%),...,CO2 Emission per kg (estimated),Waste Reduction Impact (%),Sustainability Target Progress (%),Load Handling Score,Moisture Resistance Score,Thermal Resistance Score,Cost per Unit (USD),Annual Usage (units),Total Material Weight (tons),Supplier Sustainability Compliance (%)
0,MAT_0001,Cardboard Boxes,Cardboard,"E-commerce, Food & Beverage, Consumer Goods, A...",Last-mile delivery and primary e-commerce pack...,EMEA,98.0,High,79.0,49.0,...,0.54,61.0,88.0,6.0,5.0,4.0,2.24,101260.0,790.0,85.0
1,MAT_0002,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,APAC,100.0,High,93.0,31.0,...,0.32,68.0,98.0,3.0,3.0,3.0,1.82,73961.0,545.0,88.0
2,MAT_0003,Steel Racks & Containers,Steel,"Heavy Industrial Components, High-Security Goods","Secure, high-load international shipping and l...",AMERICAS,87.0,High,78.0,100.0,...,3.25,85.0,79.0,8.0,9.0,9.0,25.00,14649.0,4979.0,88.0
3,MAT_0004,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,ROW,100.0,High,89.0,31.0,...,0.31,69.0,87.0,1.0,1.0,4.0,2.43,75036.0,656.0,81.0
4,MAT_0005,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,LATAM,100.0,High,92.0,28.0,...,0.31,61.0,89.0,3.0,2.0,3.0,1.69,69209.0,549.0,81.0

In [3]:
numeric_cols = df.select_dtypes(include=['int64','float64']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

print("Numeric Columns:", numeric_cols)
print("Categorical Columns:", categorical_cols)

Numeric Columns: ['Recyclability (%)', 'Recycled Content (%)', 'Reusability (%)', 'Biodegradation Time (days)', 'End-of-Life Disposal (%)', 'Carbon Footprint (kg CO2/unit)', 'CO2 Emission per kg (estimated)', 'Waste Reduction Impact (%)', 'Sustainability Target Progress (%)', 'Load Handling Score', 'Moisture Resistance Score', 'Thermal Resistance Score', 'Cost per Unit (USD)', 'Annual Usage (units)', 'Total Material Weight (tons)', 'Supplier Sustainability Compliance (%)']
Categorical Columns: ['Material ID', 'Packaging Type', 'Material Type', 'Suitable Product Categories', 'Recommended Packaging Use Cases', 'Supplier Region', 'Recyclability Category']

In [ ]:

ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

encoded_array = ohe.fit_transform(df[categorical_cols])


encoded_df = pd.DataFrame(
    encoded_array,
    columns=ohe.get_feature_names_out(categorical_cols)
)

encoded_df.head()

,Material ID_MAT_0001,Material ID_MAT_0002,Material ID_MAT_0003,Material ID_MAT_0004,Material ID_MAT_0005,Material ID_MAT_0006,Material ID_MAT_0007,Material ID_MAT_0008,Material ID_MAT_0009,Material ID_MAT_0010,...,Recommended Packaging Use Cases_Surface protection during transit; minimal void-fill,Recommended Packaging Use Cases_Void-fill and cushioning for fragile products,Supplier Region_AMERICAS,Supplier Region_APAC,Supplier Region_EMEA,Supplier Region_EU,Supplier Region_LATAM,Supplier Region_ROW,Recyclability Category_High,Recyclability Category_Medium
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [6]:
os.makedirs("models/encoders", exist_ok=True)
joblib.dump(ohe, "C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\models\\encoders\\ohe_encoder.pkl")

print("OHE encoder saved successfully!")

OHE encoder saved successfully!

In [7]:
scaler = MinMaxScaler()

scaled_array = scaler.fit_transform(df[numeric_cols])
scaled_df = pd.DataFrame(scaled_array, columns=numeric_cols)

scaled_df.head()

,Recyclability (%),Recycled Content (%),Reusability (%),Biodegradation Time (days),End-of-Life Disposal (%),Carbon Footprint (kg CO2/unit),CO2 Emission per kg (estimated),Waste Reduction Impact (%),Sustainability Target Progress (%),Load Handling Score,Moisture Resistance Score,Thermal Resistance Score,Cost per Unit (USD),Annual Usage (units),Total Material Weight (tons),Supplier Sustainability Compliance (%)
0,0.955556,0.794521,0.474227,0.000871,0.125000,0.139881,0.087542,0.569231,0.739130,0.555556,0.444444,0.250,0.078866,0.963447,0.130382,0.594595
1,1.000000,0.986301,0.288660,0.000189,0.000000,0.062500,0.013468,0.676923,0.956522,0.222222,0.222222,0.125,0.062549,0.659777,0.080857,0.675676
2,0.711111,0.780822,1.000000,1.000000,0.250000,1.000000,1.000000,0.938462,0.543478,0.777778,0.888889,0.875,0.963092,0.000000,0.977158,0.675676
3,1.000000,0.931507,0.288660,0.000189,0.041667,0.050595,0.010101,0.692308,0.717391,0.000000,0.000000,0.250,0.086247,0.671735,0.103295,0.486486
4,1.000000,0.972603,0.257732,0.000505,0.041667,0.029762,0.010101,0.569231,0.760870,0.222222,0.111111,0.125,0.057498,0.606917,0.081666,0.486486

In [10]:
os.makedirs("models/scalers", exist_ok=True)
joblib.dump(scaler, "C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\models\\scalers\\minmax_scaler.pkl")

print("Scaler saved successfully!")

Scaler saved successfully!

In [11]:
# Drop old categorical columns
df_numeric_only = df.drop(columns=categorical_cols)

# Combine scaled numeric + encoded categorical
final_df = pd.concat([scaled_df, encoded_df], axis=1)

final_df.head()

,Recyclability (%),Recycled Content (%),Reusability (%),Biodegradation Time (days),End-of-Life Disposal (%),Carbon Footprint (kg CO2/unit),CO2 Emission per kg (estimated),Waste Reduction Impact (%),Sustainability Target Progress (%),Load Handling Score,...,Recommended Packaging Use Cases_Surface protection during transit; minimal void-fill,Recommended Packaging Use Cases_Void-fill and cushioning for fragile products,Supplier Region_AMERICAS,Supplier Region_APAC,Supplier Region_EMEA,Supplier Region_EU,Supplier Region_LATAM,Supplier Region_ROW,Recyclability Category_High,Recyclability Category_Medium
0,0.955556,0.794521,0.474227,0.000871,0.125000,0.139881,0.087542,0.569231,0.739130,0.555556,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,1.000000,0.986301,0.288660,0.000189,0.000000,0.062500,0.013468,0.676923,0.956522,0.222222,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.711111,0.780822,1.000000,1.000000,0.250000,1.000000,1.000000,0.938462,0.543478,0.777778,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.000000,0.931507,0.288660,0.000189,0.041667,0.050595,0.010101,0.692308,0.717391,0.000000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,1.000000,0.972603,0.257732,0.000505,0.041667,0.029762,0.010101,0.569231,0.760870,0.222222,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [12]:


final_df.to_csv("C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\data\\model_ready\\materials_final_encoded.csv", index=False)

print("Model-ready dataset saved successfully!")

Model-ready dataset saved successfully!