In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
materials = pd.read_csv("data/processed/clean_materials.csv")
products = pd.read_csv("data/processed/clean_products.csv")

materials.head(), products.head()

(   material_id   material_name  density  cost_per_kg  recyclability_percent  \
 0            1       Cardboard     0.69           40                     85
 1            2             PLA     1.25          120                     60
 2            3  Recycled_Paper     0.80           30                     90

    biodegradability_percent  co2_factor industry_use_case
 0                        70         2.1         Packaging
 1                        90         1.5              Food
 2                        80         1.8       Electronics  ,
         product_name  length  width  height  weight fragility
 0       Glass Bottle      10      6      25     0.5      high
 1      Cardboard Box      30     20      15     1.2    medium
 2  Plastic Container      15     10       8     0.3       low)

In [3]:
print("Materials shape:", materials.shape)
print("Products shape:", products.shape)

Materials shape: (3, 8)
Products shape: (3, 6)

In [4]:
print(materials.columns)
print(products.columns)

Index(['material_id', 'material_name', 'density', 'cost_per_kg',
       'recyclability_percent', 'biodegradability_percent', 'co2_factor',
       'industry_use_case'],
      dtype='object')
Index(['product_name', 'length', 'width', 'height', 'weight', 'fragility'], dtype='object')

In [5]:
print(materials.dtypes)
print(products.dtypes)

material_id                   int64
material_name                object
density                     float64
cost_per_kg                   int64
recyclability_percent         int64
biodegradability_percent      int64
co2_factor                  float64
industry_use_case            object
dtype: object
product_name     object
length            int64
width             int64
height            int64
weight          float64
fragility        object
dtype: object

In [6]:
materials.tail()
products.tail()

        product_name  length  width  height  weight fragility
0       Glass Bottle      10      6      25     0.5      high
1      Cardboard Box      30     20      15     1.2    medium
2  Plastic Container      15     10       8     0.3       low

In [7]:
materials.describe()

,material_id,density,cost_per_kg,recyclability_percent,biodegradability_percent,co2_factor
count,3.0,3.000000,3.000000,3.000000,3.0,3.00
mean,2.0,0.913333,63.333333,78.333333,80.0,1.80
std,1.0,0.296704,49.328829,16.072751,10.0,0.30
min,1.0,0.690000,30.000000,60.000000,70.0,1.50
25%,1.5,0.745000,35.000000,72.500000,75.0,1.65
50%,2.0,0.800000,40.000000,85.000000,80.0,1.80
75%,2.5,1.025000,80.000000,87.500000,85.0,1.95
max,3.0,1.250000,120.000000,90.000000,90.0,2.10

In [8]:
products.describe()

          length      width     height    weight
count   3.000000   3.000000   3.000000  3.000000
mean   18.333333  12.000000  16.000000  0.666667
std    10.408330   7.211103   8.544004  0.472582
min    10.000000   6.000000   8.000000  0.300000
25%    12.500000   8.000000  11.500000  0.400000
50%    15.000000  10.000000  15.000000  0.500000
75%    22.500000  15.000000  20.000000  0.850000
max    30.000000  20.000000  25.000000  1.200000

In [9]:
materials.nunique()

material_id                 3
material_name               3
density                     3
cost_per_kg                 3
recyclability_percent       3
biodegradability_percent    3
co2_factor                  3
industry_use_case           3
dtype: int64

In [10]:
materials['industry_use_case'].value_counts()

industry_use_case
Packaging      1
Food           1
Electronics    1
Name: count, dtype: int64

In [11]:
products['fragility'].value_counts()

fragility
high      1
medium    1
low       1
Name: count, dtype: int64

In [12]:
materials.isna().sum()

material_id                 0
material_name               0
density                     0
cost_per_kg                 0
recyclability_percent       0
biodegradability_percent    0
co2_factor                  0
industry_use_case           0
dtype: int64

In [13]:
products.isna().sum()

product_name    0
length          0
width           0
height          0
weight          0
fragility       0
dtype: int64

In [14]:
materials.duplicated().sum()

np.int64(0)

In [15]:
products.duplicated().sum()

np.int64(0)

In [16]:
missing_materials = materials.isna().sum()
missing_products = products.isna().sum()

missing_df = pd.concat([missing_materials, missing_products], axis=1)
missing_df.columns = ['Materials', 'Products']

missing_df.to_csv('missing_value_table.csv')

missing_df

                          Materials  Products
material_id                     0.0       NaN
material_name                   0.0       NaN
density                         0.0       NaN
cost_per_kg                     0.0       NaN
recyclability_percent           0.0       NaN
biodegradability_percent        0.0       NaN
co2_factor                      0.0       NaN
industry_use_case               0.0       NaN
product_name                    NaN       0.0
length                          NaN       0.0
width                           NaN       0.0
height                          NaN       0.0
weight                          NaN       0.0
fragility                       NaN       0.0