In [1]:
import pandas as pd

In [6]:
materials = pd.read_csv("C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\data\\raw\\material_dataset.csv")
materials.head()

,Material ID,Packaging Type,Material Type,Suitable Product Categories,Recommended Packaging Use Cases,Supplier Region,Recyclability (%),Recyclability Category,Recycled Content (%),Reusability (%),...,CO2 Emission per kg (estimated),Waste Reduction Impact (%),Sustainability Target Progress (%),Load Handling Score,Moisture Resistance Score,Thermal Resistance Score,Cost per Unit (USD),Annual Usage (units),Total Material Weight (tons),Supplier Sustainability Compliance (%)
0,MAT_0001,Cardboard Boxes,Cardboard,"E-commerce, Food & Beverage, Consumer Goods, A...",Last-mile delivery and primary e-commerce pack...,EMEA,98,High,79.0,49.0,...,0.54,61.0,88.0,6.0,5.0,4.0,2.24,101260.0,790.0,85.0
1,MAT_0002,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,APAC,100,High,93.0,31.0,...,0.32,68.0,98.0,3.0,3.0,3.0,1.82,73961.0,545.0,88.0
2,MAT_0003,Steel Racks & Containers,Steel,"Heavy Industrial Components, High-Security Goods","Secure, high-load international shipping and l...",AMERICAS,87,High,78.0,100.0,...,3.25,85.0,79.0,8.0,9.0,9.0,25.00,14649.0,4979.0,88.0
3,MAT_0004,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,ROW,100,High,89.0,31.0,...,0.31,69.0,87.0,1.0,1.0,4.0,2.43,75036.0,656.0,81.0
4,MAT_0005,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,LATAM,100,High,92.0,28.0,...,0.31,61.0,89.0,3.0,2.0,3.0,1.69,69209.0,549.0,81.0

In [7]:
products = pd.read_csv("C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\data\\raw\\product_dataset.csv")
products.head()

,product_id,product_name,category,product_weight_kg,fragility_index,shipping_type
0,1,Chocolate Box,Food,0.5,2,Air
1,2,Smartphone,Electronics,0.3,5,Air
2,3,Perfume Bottle,Cosmetics,0.2,4,Road
3,4,Medicine Pack,Pharmacy,0.1,3,Air
4,5,Snack Pack,Food,0.7,2,Road

In [8]:
materials.shape

(404, 23)

In [9]:
products.shape

(1500, 6)

In [10]:
materials.columns

Index(['Material ID', 'Packaging Type', 'Material Type',
       'Suitable Product Categories', 'Recommended Packaging Use Cases',
       'Supplier Region', 'Recyclability (%)', 'Recyclability Category',
       'Recycled Content (%)', 'Reusability (%)', 'Biodegradation Time (days)',
       'End-of-Life Disposal (%)', 'Carbon Footprint (kg CO2/unit)',
       'CO2 Emission per kg (estimated)', 'Waste Reduction Impact (%)',
       'Sustainability Target Progress (%)', 'Load Handling Score',
       'Moisture Resistance Score', 'Thermal Resistance Score',
       'Cost per Unit (USD)', 'Annual Usage (units)',
       'Total Material Weight (tons)',
       'Supplier Sustainability Compliance (%)'],
      dtype='object')

In [11]:
products.columns

Index(['product_id', 'product_name', 'category', 'product_weight_kg',
       'fragility_index', 'shipping_type'],
      dtype='object')

In [12]:
materials.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404 entries, 0 to 403
Data columns (total 23 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Material ID                             404 non-null    object
 1   Packaging Type                          404 non-null    object
 2   Material Type                           404 non-null    object
 3   Suitable Product Categories             404 non-null    object
 4   Recommended Packaging Use Cases         404 non-null    object
 5   Supplier Region                         404 non-null    object
 6   Recyclability (%)                       404 non-null    int64
 7   Recyclability Category                  404 non-null    object
 8   Recycled Content (%)                    403 non-null    float64
 9   Reusability (%)                         403 non-null    float64
 10  Biodegradation Time (days)              403 non-null    float64
 11  End-of-Life Disposal (%)                403 non-null    float64
 12  Carbon Footprint (kg CO2/unit)          403 non-null    float64
 13  CO2 Emission per kg (estimated)         403 non-null    float64
 14  Waste Reduction Impact (%)              403 non-null    float64
 15  Sustainability Target Progress (%)      403 non-null    float64
 16  Load Handling Score                     403 non-null    float64
 17  Moisture Resistance Score               403 non-null    float64
 18  Thermal Resistance Score                403 non-null    float64
 19  Cost per Unit (USD)                     403 non-null    float64
 20  Annual Usage (units)                    403 non-null    float64
 21  Total Material Weight (tons)            403 non-null    float64
 22  Supplier Sustainability Compliance (%)  403 non-null    float64
dtypes: float64(15), int64(1), object(7)
memory usage: 72.7+ KB

In [13]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         1500 non-null   int64
 1   product_name       1500 non-null   object
 2   category           1500 non-null   object
 3   product_weight_kg  1500 non-null   float64
 4   fragility_index    1500 non-null   int64
 5   shipping_type      1500 non-null   object
dtypes: float64(1), int64(2), object(3)
memory usage: 70.4+ KB

In [14]:
materials.isnull().sum()

Material ID                               0
Packaging Type                            0
Material Type                             0
Suitable Product Categories               0
Recommended Packaging Use Cases           0
Supplier Region                           0
Recyclability (%)                         0
Recyclability Category                    0
Recycled Content (%)                      1
Reusability (%)                           1
Biodegradation Time (days)                1
End-of-Life Disposal (%)                  1
Carbon Footprint (kg CO2/unit)            1
CO2 Emission per kg (estimated)           1
Waste Reduction Impact (%)                1
Sustainability Target Progress (%)        1
Load Handling Score                       1
Moisture Resistance Score                 1
Thermal Resistance Score                  1
Cost per Unit (USD)                       1
Annual Usage (units)                      1
Total Material Weight (tons)              1
Supplier Sustainability Compliance (%)    1
dtype: int64

In [15]:
products.isnull().sum()

product_id           0
product_name         0
category             0
product_weight_kg    0
fragility_index      0
shipping_type        0
dtype: int64

In [16]:
materials.describe()

,Recyclability (%),Recycled Content (%),Reusability (%),Biodegradation Time (days),End-of-Life Disposal (%),Carbon Footprint (kg CO2/unit),CO2 Emission per kg (estimated),Waste Reduction Impact (%),Sustainability Target Progress (%),Load Handling Score,Moisture Resistance Score,Thermal Resistance Score,Cost per Unit (USD),Annual Usage (units),Total Material Weight (tons),Supplier Sustainability Compliance (%)
count,404.000000,403.000000,403.000000,403.000000,403.000000,403.000000,403.000000,403.000000,403.000000,403.000000,403.000000,403.000000,403.000000,403.000000,403.000000,403.000000
mean,91.613861,61.833747,66.694789,31396.910670,9.039702,1.186774,1.148387,68.034739,83.997519,6.498759,6.059553,5.697270,8.935931,67070.555831,1153.957816,87.466501
std,8.584966,19.340228,28.766147,37072.185094,5.561811,0.748728,0.720590,13.839297,9.015878,2.094027,2.470004,1.870873,7.092944,26822.383226,1099.929480,7.283235
min,55.000000,21.000000,3.000000,31.000000,2.000000,0.310000,0.280000,24.000000,54.000000,1.000000,1.000000,2.000000,0.210000,14649.000000,145.000000,63.000000
25%,87.000000,47.500000,48.000000,197.000000,5.000000,0.780000,0.510000,60.000000,82.000000,5.000000,4.000000,4.000000,2.810000,49673.000000,743.000000,85.000000
50%,94.000000,68.000000,53.000000,28329.000000,8.000000,0.990000,1.400000,69.000000,86.000000,7.000000,7.000000,6.000000,3.870000,59942.000000,901.000000,88.000000
75%,99.000000,79.000000,95.000000,50709.500000,11.000000,1.180000,1.500000,79.000000,90.000000,8.000000,8.000000,7.000000,14.650000,96931.500000,1072.000000,92.000000
max,100.000000,94.000000,100.000000,180208.000000,26.000000,3.670000,3.250000,89.000000,100.000000,10.000000,10.000000,10.000000,25.950000,104546.000000,5092.000000,100.000000

In [17]:
products.describe()

        product_id  product_weight_kg  fragility_index
count  1500.000000        1500.000000      1500.000000
mean    750.500000           0.925087         2.617333
std     433.157015           1.604414         1.087361
min       1.000000           0.040000         1.000000
25%     375.750000           0.300000         2.000000
50%     750.500000           0.520000         3.000000
75%    1125.250000           0.900000         3.000000
max    1500.000000          15.000000         5.000000

In [18]:
materials.select_dtypes(include='object').head()

,Material ID,Packaging Type,Material Type,Suitable Product Categories,Recommended Packaging Use Cases,Supplier Region,Recyclability Category
0,MAT_0001,Cardboard Boxes,Cardboard,"E-commerce, Food & Beverage, Consumer Goods, A...",Last-mile delivery and primary e-commerce pack...,EMEA,High
1,MAT_0002,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,APAC,High
2,MAT_0003,Steel Racks & Containers,Steel,"Heavy Industrial Components, High-Security Goods","Secure, high-load international shipping and l...",AMERICAS,High
3,MAT_0004,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,ROW,High
4,MAT_0005,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,LATAM,High

In [19]:
products.select_dtypes(include='object').head()

     product_name     category shipping_type
0   Chocolate Box         Food           Air
1      Smartphone  Electronics           Air
2  Perfume Bottle    Cosmetics          Road
3   Medicine Pack     Pharmacy           Air
4      Snack Pack         Food          Road

## EDA Observations

- Materials dataset has ___ rows and ___ columns
- Products dataset has ___ rows and ___ columns
- Some columns contain missing values
- Numerical columns show varying ranges
- Categorical columns contain text data