In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [4]:
materials = pd.read_csv("C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\data\\processed\\materials_cleaned.csv")
products = pd.read_csv("C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\data\\processed\\products_cleaned.csv")

In [15]:
print(materials.columns)

Index(['Material ID', 'Packaging Type', 'Material Type',
       'Suitable Product Categories', 'Recommended Packaging Use Cases',
       'Supplier Region', 'Recyclability (%)', 'Recyclability Category',
       'Recycled Content (%)', 'Reusability (%)', 'Biodegradation Time (days)',
       'End-of-Life Disposal (%)', 'Carbon Footprint (kg CO2/unit)',
       'CO2 Emission per kg (estimated)', 'Waste Reduction Impact (%)',
       'Sustainability Target Progress (%)', 'Load Handling Score',
       'Moisture Resistance Score', 'Thermal Resistance Score',
       'Cost per Unit (USD)', 'Annual Usage (units)',
       'Total Material Weight (tons)',
       'Supplier Sustainability Compliance (%)'],
      dtype='object')

In [16]:
materials_num = materials.select_dtypes(include=["int64", "float64"])

In [17]:
materials_cat = materials.select_dtypes(include=["object"])

In [18]:
from sklearn.preprocessing import LabelEncoder

for col in materials_cat.columns:
    le = LabelEncoder()
    materials_cat[col] = le.fit_transform(materials_cat[col].astype(str))

In [19]:
materials_ml = pd.concat([materials_num, materials_cat], axis=1)

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
materials_scaled = scaler.fit_transform(materials_ml)

materials_final = pd.DataFrame(
    materials_scaled,
    columns=materials_ml.columns
)

In [21]:
materials_final.to_csv("C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\data\\final\\materials_ml_ready.csv")

In [22]:
products = pd.read_csv("C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\data\\processed\\products_cleaned.csv")

In [23]:
products.head()
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         1500 non-null   int64
 1   product_name       1500 non-null   object
 2   category           1500 non-null   object
 3   product_weight_kg  1500 non-null   float64
 4   fragility_index    1500 non-null   int64
 5   shipping_type      1500 non-null   object
dtypes: float64(1), int64(2), object(3)
memory usage: 70.4+ KB

In [24]:
products_num = products.select_dtypes(include=["int64", "float64"])
products_num.head()

   product_id  product_weight_kg  fragility_index
0           1                0.5                2
1           2                0.3                5
2           3                0.2                4
3           4                0.1                3
4           5                0.7                2

In [25]:
products_cat = products.select_dtypes(include=["object"])
products_cat.head()

     product_name     category shipping_type
0   Chocolate Box         Food           Air
1      Smartphone  Electronics           Air
2  Perfume Bottle    Cosmetics          Road
3   Medicine Pack     Pharmacy           Air
4      Snack Pack         Food          Road

In [26]:
from sklearn.preprocessing import LabelEncoder

for col in products_cat.columns:
    le = LabelEncoder()
    products_cat[col] = le.fit_transform(products_cat[col].astype(str))

In [27]:
products_ml = pd.concat([products_num, products_cat], axis=1)
products_ml.head()

,product_id,product_weight_kg,fragility_index,product_name,category,shipping_type
0,1,0.5,2,169,4,0
1,2,0.3,5,1100,3,0
2,3,0.2,4,866,1,1
3,4,0.1,3,725,6,0
4,5,0.7,2,1186,4,1

In [28]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
products_scaled = scaler.fit_transform(products_ml)

products_final = pd.DataFrame(
    products_scaled,
    columns=products_ml.columns
)

In [29]:
products_final.to_csv("C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\data\\final\\product_ml_ready.csv", index=False)

In [30]:
products_final.shape
products_final.head()

,product_id,product_weight_kg,fragility_index,product_name,category,shipping_type
0,-1.730896,-0.265037,-0.567925,-1.337471,0.314023,-1.336760
1,-1.728587,-0.389734,2.191968,0.844911,-0.293764,-1.336760
2,-1.726278,-0.452083,1.272004,0.296385,-1.509338,0.419054
3,-1.723968,-0.514432,0.352040,-0.034137,1.529597,-1.336760
4,-1.721659,-0.140339,-0.567925,1.046506,0.314023,0.419054

In [32]:
import pandas as pd
import joblib
from sklearn.preprocessing import LabelEncoder, StandardScaler

materials = pd.read_csv("C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\data\\processed\\materials_cleaned.csv")

In [33]:
num_cols = materials.select_dtypes(include=["int64", "float64"]).columns
cat_cols = materials.select_dtypes(include=["object"]).columns

In [34]:
encoders = {}

for col in cat_cols:
    le = LabelEncoder()
    materials[col] = le.fit_transform(materials[col].astype(str))
    encoders[col] = le

joblib.dump(encoders, "C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\models\\encoders\\material_encoders.pkl")

['C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\models\\encoders\\material_encoders.pkl']

In [35]:
scaler = StandardScaler()
materials[num_cols] = scaler.fit_transform(materials[num_cols])

joblib.dump(scaler, "C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\models\\scalers\\material_scaler.pkl")

['C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\models\\scalers\\material_scaler.pkl']

In [31]:
materials_final.to_csv(
    "C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\data\\model_ready\\material_final_encoded.csv",
    index=False
)

materials_final.to_parquet(
    "C:\\Users\\sneha\\Desktop\\AI-Powered-Sustainable-Packaging-Recommendation-System\\data\\model_ready\\mterials_final_encoded.parquet",
    index=False
)